### ISSUE TITLE
Code for training the model

### ISSUE THREAD

**Issue by saisritejakuppa** [hkproj/pytorch-stable-diffusion#1]
Can you also write a simple file for training a database of images? @hkproj

**Comment by TWang1017** [comment]
yesss, appreciate that if anyone can give a simple training code

**Comment by Inkyl** [comment]
I'm also looking forward to finding a training code from scratch @hkproj

**Comment by hkproj** [comment]
Hi! I don't have any immediate plan to write the training code, especially because this code is meant for learning the model and not to be used in production. If you'd like to train the model for fine-tuning or for production, I highly recommend using Hugging Face.

If you want to learn how training works for Stable Diffusion, then, given that we are using the DDPM formulation in my video, you only need to train the using the Algorithm described in [my video on Diffusion Models](https://www.youtube.com/watch?v=I1sPXkm2NH4), in which I also provide the code for the training algorithm. The implementation of that video can be found in [my repository about the DDPM paper](https://github.com/hkproj/pytorch-ddpm).

The only difference is that you also need to provide the time step and the caption of the image you're training the model upon, since they're both inputs for the UNet.

But as I've said before, for training a model from scratch, I highly recommend using open source libraries like Hugging Face, because it also takes into consideration all the data augmentation needed for the model. Be aware that to train a working Stable Diffusion from scratch that can generate meaningful outputs, it needs millions of images, which may take forever if you're using your personal computer/laptop.
